### ISSUE TITLE
Custom keyboard

### ISSUE THREAD

**Issue by Tefofo** [CodeIsAnArt/VirtualKeyboard#1]
Hi @Droidlover,

Is it possible for one to customise the keyboard; to have say only numeric or alphanumeric?

**Comment by CodeIsAnArt** [comment]
@Tefofo  check out npm!

**Comment by Tefofo** [comment]
@CodeIsAnArt Thank you will check it out!

**Comment by Tefofo** [comment]
@CodeIsAnArt that is great! One more thing, how do you use the customizations?
I can see you did not update the ReadMe.md file

**Comment by CodeIsAnArt** [comment]
I didnt get you...What do you mean by customizations!?

**Comment by Tefofo** [comment]
Hi @CodeIsAnArt ,

I meant that you can hook up your own custom keyboard configuration, make the component to receive a custom configuration. I see that you introduced a new property kboardType, my question is how do you tell the component that you want to use kboardType=numeric?

**Comment by Tefofo** [comment]
Hi @CodeIsAnArt ,
I am still new in Angular and still learning....so I don't understand how kboardType input works on this particular directive, hence the many questions. 
Sorry if I am asking too much but I would really like to understand the usage, I can't seem to get it working in my App with only numeric options.

**Comment by Tefofo** [comment]
Hi @CodeIsAnArt ....I managed to get it to work thanks!
